site_name: ZYJ's Blog

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Analog IC: './analog/analog_home.md'